import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import Tareas from "../components/TareasOriginal"
import { useEffect } from 'react';
import cookie from "js-cookie";
import Script from 'next/script';

export default function Home() {


  const [arrayObjetos, setArrayObjetos] = useState([]);
  const [nombre, setNombre] = useState('');
  const [descripcion, setDescripcion] = useState('');
  const [descripcionSubtarea, setDescripcionSubtarea] = useState("");

  const cookieValue = cookie.get("cookie");

  useEffect(() => {
    if (cookieValue) {
      const parsed = JSON.parse(cookieValue);
      setArrayObjetos(parsed);
    } else {
      console.log("cookie vacía o no existe");
    }
  }, []);

  useEffect(() => {
    cookie.set("cookie", JSON.stringify(arrayObjetos));
  }, [arrayObjetos]);

  function deleteCookies() {
    cookie.remove('cookie');
  }

  const handleSubmit = (e) => {
    e.preventDefault();
    const nuevoObjeto = { nombre, descripcion, openTask: true, susbtareas: [] };
    setArrayObjetos([...arrayObjetos, nuevoObjeto]);
    setNombre('');
    setDescripcion('');
    console.log(arrayObjetos)
  }


  //Subtareas
  const handleAddAndSubmitSubtarea = (e, index) => {
    e.preventDefault();
    const newArrayObjetos = [...arrayObjetos];
    if (!newArrayObjetos[index].subtareas) {
      newArrayObjetos[index].subtareas = [];
    }
    newArrayObjetos[index].subtareas.push({ descripcion: descripcionSubtarea });
    setArrayObjetos(newArrayObjetos);
    setDescripcionSubtarea("");
  }




  const handleDeleteSubtarea = (indexParent, indexSubtarea) => {
    const newArrayObjetos = [...arrayObjetos];
    newArrayObjetos[indexParent].subtareas.splice(indexSubtarea, 1);
    setArrayObjetos(newArrayObjetos);
    cookie.set("cookie", JSON.stringify(arrayObjetos));
  }



  const handleChangeOpenTask = (index) => {
    const newArrayObjetos = [...arrayObjetos];
    newArrayObjetos[index].openTask = !newArrayObjetos[index].openTask;
    setArrayObjetos(newArrayObjetos);
  }

  const handleDelete = (index) => {
    const newArrayObjetos = [...arrayObjetos];
    newArrayObjetos.splice(index, 1);
    setArrayObjetos(newArrayObjetos);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <header>
          <nav
            className="d-flex navbar navbar-light navbar-expand-md"
            style={{
              paddingTop: 30,
              paddingBottom: 30,
              paddingRight: "var(--padding-r-t2)",
              paddingLeft: "var(--padding-l-t2)",
              width: "100%",
              background: "#fff"
            }}
          >
            <div className="d-flex" style={{ width: "100%" }}>
              <img src="assets/img/2222.svg" />
              <button
                className="navbar-toggler"
                data-bs-toggle="collapse"
                data-bs-target="#navcol-1"
                style={{ padding: 0 }}
              >
                <span className="visually-hidden">Toggle navigation</span>
                <span className="navbar-toggler-icon" />
              </button>
              <div className="collapse navbar-collapse" id="navcol-1">
                <ul className="nav ms-auto" style={{ display: "none", gap: 30 }}>
                  <li className="nav-item">
                    <a className="nav-link nav-item" href="#" style={{ padding: 0 }}>
                      Inicio
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link nav-item" href="#" style={{ padding: 0 }}>
                      Precios
                    </a>
                  </li>
                  <li className="nav-item">
                    <a
                      className="nav-link active nav-item"
                      href="#"
                      style={{ padding: 0 }}
                    >
                      Generador de contraseñas
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        <section
          className="d-flex flex-row align-items-start"
          style={{
            paddingLeft: "var(--padding-l-t3)",
            paddingRight: "var(--padding-r-t3)",
            minHeight: 500,
            paddingTop: 60,
            paddingBottom: 100
          }}
        >
          <div className="d-flex flex-column" style={{ width: "100%", gap: 40 }}>
            <div className="d-flex justify-content-between align-items-center">
              <h1
                style={{
                  fontSize: "var(--font-titulo2-font-size)",
                  fontFamily: "var(--font-titulo1-font-family)",
                  fontWeight: 600,
                  color: "#000",
                  margin: 0
                }}
              >
                Mis tareas
              </h1>
              <button
                className="btn btn-primary"
                id="abrir-crearTarea"
                type="button"
                style={{
                  padding: "15px 30px",
                  fontSize: 14,
                  fontWeight: 600,
                  fontFamily: '"outfit", sans-serif',
                  minWidth: "fit-content",
                  background: "var(--color-primary-800)",
                  borderRadius: 20,
                  border: "none !important"
                }}
              >
                Añadir nueva tarea
              </button>
            </div>
            <div className="d-flex flex-column" style={{ gap: 40 }}>
              <div style={{ padding: 40, background: "#fff", borderRadius: 20 }}>
                <div
                  className="d-flex flex-row justify-content-between align-items-start"
                  style={{ position: "relative" }}
                >
                  <div className="d-flex" style={{ gap: 16 }}>
                    <input
                      type="checkbox"
                      className="form-check-input"
                      defaultChecked=""
                      style={{
                        padding: 16,
                        marginTop: 3,
                        borderColor: "var(--color-primary-800)",
                        borderRadius: 10
                      }}
                    />
                    <div>
                      <h1
                        style={{
                          fontSize: "var(--font-titulo3-font-size)",
                          fontFamily: "var(--font-titulo1-font-family)",
                          fontWeight: 500,
                          color: "#000",
                          marginBottom: 4
                        }}
                      >
                        Client review &amp; feedback
                        <br />
                      </h1>
                      <p
                        style={{
                          fontSize: "var(--font-smallText-font-size)",
                          fontFamily: "var(--font-titulo1-font-family)",
                          fontWeight: 300,
                          color: "#000",
                          marginBottom: 30
                        }}
                      >
                        Soy la descripción de esta tarea
                      </p>
                    </div>
                  </div>
                  <button
                    className="btn btn-primary"
                    type="button"
                    style={{
                      padding: 0,
                      fontSize: 14,
                      fontWeight: 600,
                      fontFamily: '"outfit", sans-serif',
                      minWidth: "fit-content",
                      background: "#fff",
                      borderRadius: 10,
                      borderStyle: "none",
                      color: "var(--color-primary-800)"
                    }}
                  >
                    <img
                      id="configBox-principal-open"
                      src="assets/img/fi-br-menu-dots.svg"
                      style={{ height: 20, width: 20 }}
                    />
                  </button>
                  <div
                    className="flex-column"
                    id="configBox-principal"
                    style={{
                      position: "absolute",
                      right: 0,
                      top: 36,
                      background: "#fff",
                      padding: 20,
                      borderRadius: 10,
                      boxShadow: "0px 0px 15px rgba(0,0,0,0.05)",
                      gap: 12,
                      display: "none",
                      zIndex: 2
                    }}
                  >
                    <button
                      className="btn btn-primary d-flex"
                      id="agregarSubtarea-btn"
                      type="button"
                      style={{
                        background: "rgba(222,5,5,0)",
                        fontSize: 14,
                        fontWeight: 600,
                        fontFamily: '"outfit", sans-serif',
                        minWidth: "fit-content",
                        color: "var(--color-primary-800)",
                        borderRadius: 20,
                        border: "none !important",
                        gap: 8,
                        lineHeight: "100%"
                      }}
                    >
                      <img
                        style={{ width: 14, height: 14 }}
                        src="assets/img/fi-br-plus.svg"
                      />
                      Agregar Subtarea
                    </button>
                    <button
                      className="btn btn-primary d-flex"
                      id="borrarTareaBtn"
                      type="button"
                      style={{
                        fontSize: 14,
                        fontWeight: 600,
                        fontFamily: '"outfit", sans-serif',
                        minWidth: "fit-content",
                        background: "#fff",
                        borderRadius: 20,
                        border: "none !important",
                        color: "rgb(222,5,5)",
                        gap: 8,
                        lineHeight: "100%"
                      }}
                    >
                      <img
                        src="assets/img/fi-br-cross.png"
                        style={{ width: 14, height: 14 }}
                      />
                      Borrar tarea
                    </button>
                  </div>
                </div>
                <div
                  className="justify-content-center align-items-center"
                  id="box-crearSubtarea"
                  style={{
                    position: "fixed",
                    width: "100vw",
                    left: 0,
                    top: 0,
                    minHeight: "100vh",
                    background: "rgba(0,0,0,0.4)",
                    zIndex: 10,
                    padding: 136,
                    display: "none"
                  }}
                >
                  <div>
                    <div
                      className="d-flex flex-column"
                      style={{
                        background: "#fff",
                        padding: 40,
                        borderRadius: 20,
                        gap: 16
                      }}
                    >
                      <div>
                        <h1
                          style={{
                            fontSize: "var(--font-body-font-size)",
                            fontFamily: "var(--font-titulo1-font-family)",
                            fontWeight: 600,
                            color: "#000",
                            margin: 0
                          }}
                        >
                          Creemos una subtarea 🤯
                        </h1>
                      </div>
                      <div
                        className="d-flex flex-column align-items-start"
                        style={{ gap: 16, marginBottom: 30 }}
                      >
                        <div className="d-flex" style={{ gap: 8 }}>
                          <input
                            type="text"
                            placeholder="Ingresa el título"
                            style={{
                              padding: "15px 30px",
                              borderRadius: 20,
                              borderStyle: "none",
                              background: "rgba(31,27,198,0.05)",
                              fontFamily: '"outfit", sans-serif',
                              fontSize: 14
                            }}
                          />
                          <input
                            type="text"
                            placeholder="Ingresa la descripción"
                            style={{
                              padding: "15px 30px",
                              borderRadius: 20,
                              borderStyle: "none",
                              background: "rgba(31,27,198,0.05)",
                              fontFamily: '"outfit", sans-serif',
                              fontSize: 14
                            }}
                          />
                        </div>
                        <div className="d-flex" style={{ gap: 8 }}>
                          <button
                            className="btn btn-primary"
                            id="crearSubtareaBtn"
                            type="button"
                            style={{
                              padding: "15px 30px",
                              fontSize: 14,
                              fontWeight: 600,
                              fontFamily: '"outfit", sans-serif',
                              minWidth: "fit-content",
                              background: "var(--color-primary-800)",
                              borderRadius: 20,
                              border: "none !important"
                            }}
                          >
                            Crear subtarea
                          </button>
                          <button
                            className="btn btn-primary"
                            id="cerrar-crearSubtarea"
                            type="button"
                            style={{
                              padding: "15px 30px",
                              fontSize: 14,
                              fontWeight: 600,
                              fontFamily: '"outfit", sans-serif',
                              minWidth: "fit-content",
                              background: "#fff",
                              borderRadius: 20,
                              borderStyle: "solid",
                              borderWidth: 1,
                              color: "var(--color-primary-800)",
                              borderColor: "var(--color-primary-800) !important"
                            }}
                          >
                            Cancelar
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div style={{ paddingLeft: 50 }}>
                  <h1
                    style={{
                      fontSize: "var(--font-body-font-size)",
                      fontFamily: "var(--font-titulo1-font-family)",
                      fontWeight: 600,
                      color: "#000",
                      marginBottom: 15
                    }}
                  >
                    Subtareas
                  </h1>
                  <div style={{ display: "flex", gap: 16, flexDirection: "column" }}>
                    <div
                      className="d-flex justify-content-between align-items-start"
                      style={{ position: "relative" }}
                    >
                      <div className="d-flex" style={{ gap: 8 }}>
                        <input
                          type="checkbox"
                          className="form-check-input"
                          defaultChecked=""
                          style={{
                            padding: 9,
                            marginTop: 3,
                            borderColor: "var(--color-primary-800)",
                            borderRadius: 10
                          }}
                        />
                        <div>
                          <h1
                            style={{
                              fontSize: "var(--font-body-font-size)",
                              fontFamily: "var(--font-titulo1-font-family)",
                              fontWeight: 500,
                              color: "#000",
                              marginBottom: 0
                            }}
                          >
                            Client review &amp; feedback
                            <br />
                          </h1>
                          <p
                            style={{
                              fontSize: "var(--font-smallText-font-size)",
                              fontFamily: "var(--font-titulo1-font-family)",
                              fontWeight: 300,
                              color: "#000",
                              marginBottom: 0
                            }}
                          >
                            Soy la descripción de esta tarea
                          </p>
                        </div>
                      </div>
                      <button
                        className="btn btn-primary"
                        type="button"
                        style={{
                          padding: 0,
                          fontSize: 14,
                          fontWeight: 600,
                          fontFamily: '"outfit", sans-serif',
                          minWidth: "fit-content",
                          background: "#fff",
                          borderRadius: 10,
                          borderStyle: "none",
                          color: "var(--color-primary-800)"
                        }}
                      >
                        <img
                          id="configBox-sub-open"
                          src="assets/img/fi-br-menu-dots.svg"
                          style={{ height: 20, width: 20 }}
                        />
                      </button>
                      <div
                        className="flex-column"
                        id="configBox-sub"
                        style={{
                          position: "absolute",
                          right: 0,
                          top: 36,
                          background: "#fff",
                          padding: 20,
                          borderRadius: 10,
                          boxShadow: "0px 0px 15px rgba(0,0,0,0.05)",
                          gap: 12,
                          display: "none",
                          zIndex: 2
                        }}
                      >
                        <button
                          className="btn btn-primary d-flex"
                          id="borrarSubtarea-btn"
                          type="button"
                          style={{
                            fontSize: 14,
                            fontWeight: 600,
                            fontFamily: '"outfit", sans-serif',
                            minWidth: "fit-content",
                            background: "#fff",
                            borderRadius: 20,
                            border: "none !important",
                            color: "rgb(222,5,5)",
                            gap: 8,
                            lineHeight: "100%"
                          }}
                        >
                          <img
                            src="assets/img/fi-br-cross.png"
                            style={{ width: 14, height: 14 }}
                          />
                          Borrar subtarea
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section
          className="flex-row justify-content-center align-items-center"
          id="box-crearTarea"
          style={{
            position: "fixed",
            top: 0,
            zIndex: 10,
            background: "rgba(0,0,0,0.4)",
            width: "100vw",
            minHeight: "100vh",
            maxHeight: "100vh",
            padding: 136,
            display: "none"
          }}
        >
          <div
            className="d-flex flex-column"
            style={{ background: "#fff", padding: 40, borderRadius: 20, gap: 24 }}
          >
            <div>
              <h1
                style={{
                  fontSize: "var(--font-titulo3-font-size)",
                  fontFamily: "var(--font-titulo1-font-family)",
                  fontWeight: 600,
                  color: "#000",
                  margin: 0
                }}
              >
                Creemos una tarea 🤯
              </h1>
            </div>
            <div className="d-flex flex-column align-items-start" style={{ gap: 16 }}>
              <div className="d-flex" style={{ gap: 8 }}>
                <input
                  type="text"
                  placeholder="Ingresa el título"
                  style={{
                    padding: "15px 30px",
                    borderRadius: 20,
                    borderStyle: "none",
                    background: "rgba(31,27,198,0.05)",
                    fontFamily: '"outfit", sans-serif',
                    fontSize: 14
                  }}
                />
                <input
                  type="text"
                  placeholder="Ingresa la descripción"
                  style={{
                    padding: "15px 30px",
                    borderRadius: 20,
                    borderStyle: "none",
                    background: "rgba(31,27,198,0.05)",
                    fontFamily: '"outfit", sans-serif',
                    fontSize: 14
                  }}
                />
              </div>
              <div className="d-flex" style={{ gap: 8 }}>
                <button
                  className="btn btn-primary"
                  id="crearTareaBtn"
                  type="button"
                  style={{
                    padding: "15px 30px",
                    fontSize: 14,
                    fontWeight: 600,
                    fontFamily: '"outfit", sans-serif',
                    minWidth: "fit-content",
                    background: "var(--color-primary-800)",
                    borderRadius: 20,
                    border: "none !important"
                  }}
                >
                  Crear tarea
                </button>
                <button
                  className="btn btn-primary"
                  id="cerrar-crearTarea"
                  type="button"
                  style={{
                    padding: "15px 30px",
                    fontSize: 14,
                    fontWeight: 600,
                    fontFamily: '"outfit", sans-serif',
                    minWidth: "fit-content",
                    background: "#fff",
                    borderRadius: 20,
                    borderStyle: "solid",
                    borderWidth: 1,
                    color: "var(--color-primary-800)",
                    borderColor: "var(--color-primary-800) !important"
                  }}
                >
                  Cancelar
                </button>
              </div>
            </div>
          </div>
        </section>

        <Script src="../assets/js/crearTarea.js" />
        <Script src="../assets/bootstrap/js/bootstrap.min.js" />

      </main>
    </>
  )
}



